-- MySQL Script generated by MySQL Workbench
-- Wed Aug  5 17:49:55 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema association
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema association
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `association` DEFAULT CHARACTER SET utf8 ;
USE `association` ;

-- -----------------------------------------------------
-- Table `association`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `association`.`User` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(70) NOT NULL,
  `lastname` VARCHAR(70) NOT NULL,
  `email` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `association`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `association`.`Role` (
  `id_role` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(70) NOT NULL,
  `User_id_user` INT NOT NULL,
  PRIMARY KEY (`id_role`, `User_id_user`),
  INDEX `fk_Role_User_idx` (`User_id_user` ASC),
  CONSTRAINT `fk_Role_User`
    FOREIGN KEY (`User_id_user`)
    REFERENCES `association`.`User` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `association`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `association`.`Category` (
  `id_category` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`id_category`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `association`.`Article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `association`.`Article` (
  `id_article` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(70) NOT NULL,
  `message` VARCHAR(255) NOT NULL,
  `date` DATE NOT NULL,
  `User_id_user` INT NOT NULL,
  `Category_id_category` INT NOT NULL,
  PRIMARY KEY (`id_article`, `User_id_user`, `Category_id_category`),
  INDEX `fk_Article_User1_idx` (`User_id_user` ASC),
  INDEX `fk_Article_Category1_idx` (`Category_id_category` ASC),
  CONSTRAINT `fk_Article_User1`
    FOREIGN KEY (`User_id_user`)
    REFERENCES `association`.`User` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Article_Category1`
    FOREIGN KEY (`Category_id_category`)
    REFERENCES `association`.`Category` (`id_category`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `association`.`Comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `association`.`Comment` (
  `id_comment` INT NOT NULL AUTO_INCREMENT,
  `message` VARCHAR(150) NOT NULL,
  `date` DATE NOT NULL,
  `User_id_user` INT NOT NULL,
  `Article_id_article` INT NOT NULL,
  PRIMARY KEY (`id_comment`, `User_id_user`, `Article_id_article`),
  INDEX `fk_Comment_User1_idx` (`User_id_user` ASC),
  INDEX `fk_Comment_Article1_idx` (`Article_id_article` ASC),
  CONSTRAINT `fk_Comment_User1`
    FOREIGN KEY (`User_id_user`)
    REFERENCES `association`.`User` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comment_Article1`
    FOREIGN KEY (`Article_id_article`)
    REFERENCES `association`.`Article` (`id_article`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `association`.`Post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `association`.`Post` (
  `id_post` INT NOT NULL AUTO_INCREMENT,
  `message` VARCHAR(255) NOT NULL,
  `date` DATE NOT NULL,
  `Category_id_category` INT NOT NULL,
  `User_id_user` INT NOT NULL,
  PRIMARY KEY (`id_post`, `Category_id_category`, `User_id_user`),
  INDEX `fk_Post_Category1_idx` (`Category_id_category` ASC),
  INDEX `fk_Post_User1_idx` (`User_id_user` ASC),
  CONSTRAINT `fk_Post_Category1`
    FOREIGN KEY (`Category_id_category`)
    REFERENCES `association`.`Category` (`id_category`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Post_User1`
    FOREIGN KEY (`User_id_user`)
    REFERENCES `association`.`User` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
